version: '3.1'

services:

  redis:
    container_name: 'redis'
    hostname:
      redis
    image: redis
    ports:
      - "6379:6379"

  celery:
    container_name: 'celery_worker'
    image: celery_and_redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/code/
    command:
      ./entrypoint.celery.sh
    env_file:
      - .env
    depends_on:
      - redis

  backend:
    container_name: 'django_backend'
    image: celery_and_redis
    volumes:
      - ./backend/:/code/
    command:
      ./entrypoint.backend.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - celery
